//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Managers
    {
        public int ManagerID { get; set; }
        public string FullName_FirstName { get; set; }
        public string FullName_SecondName { get; set; }
        public string FullName_ThirdName { get; set; }
        public string FullName_LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Age { get; set; }
        public int SchoolID { get; set; }
        public int UserID { get; set; }
    
        public virtual Schools Schools { get; set; }
        public virtual Users Users { get; set; }
    }
}
